language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - make
compiler:
  - gcc
before_install:
  - export CC=/usr/bin/gcc-4.9
  - export CXX=/usr/bin/g++-4.9
script:
  - make
notifications:
  recipients:
    - christian@kakesa.net
  email:
    on_success: change
    on_failure: always
