language: cpp
compiler:
  - gcc-4.9
  - gcc-5
  - clang-3.2
#before_install:
#  - sudo apt-get -qq update
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#  - sudo apt-get update -qq
#  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
script:
  - make
notifications:
  recipients:
    - christian@kakesa.net
  email:
    on_success: change
    on_failure: always
